---
Parameters:
  vsz:
    Type: Number
Resources:
  v1:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: ap-southeast-1a
      Size: 
        Ref: vsz
      VolumeType: gp2
Outputs:
  v1id:
    Value:
      Ref: v1