---
Resources:
  vpc1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/24'
      Tags:
      - Key: Name
        Value: CFVPC
  sn1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: '10.0.0.0/25'
      AvailabilityZone: ap-southeast-1a
      VpcId:
        Ref: vpc1
      Tags:
      - Key: Name
        Value: Sn1-CFVPC 
  sn2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: '10.0.0.128/25'
      AvailabilityZone: ap-southeast-1b
      VpcId:
        Ref: vpc1
      Tags:
      - Key: Name
        Value: Sn2-CFVPC
  sg1:
     Type: AWS::EC2::SecurityGroup
     Properties:
       GroupName: SG1CF
       GroupDescription: SG1CF
       VpcId:
         Ref: vpc1
       SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: '22'
         ToPort: '22'
         CidrIp: '0.0.0.0/0'         
       - IpProtocol: tcp
         FromPort: '80'
         ToPort: '80'
         CidrIp: '20.0.0.90/32'             
  i1:
     Type: AWS::EC2::Instance
     Properties:
       ImageId: ami-0bd6906508e74f692
       InstanceType: t2.micro
       SubnetId:
         Ref: sn1       
Outputs:
  i1ip:
    Value:
      Fn::GetAtt:
      - i1
      - PrivateIp